version: 0.0
os: linux
files:
  - source: /target/myweb.war
    destination: /opt/tomcat8/webapps
    
hooks:
  BeforeInstall:
    - location: stop_tomcat.sh
      runas: ec2-user
  AfterInstall:
    - location: start_tomcat.sh
      timeout: 30
      runas: ec2-user
      
